django_invoice/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fact_app.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

fact_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('add-customer', views.AddCustomerView.as_view(), name="add-customer"),

]

fact_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Customer(models.Model):

    """
    Name: Customer Name definition
    Description:
    author: evjeanbaptiste@gmail.com
    """
    
    SEX_TYPES = (
        ('M', 'Masculin'),
        ('F', 'Féminin'),
    )

    name = models.CharField(max_length=132)
    email = models.EmailField()
    phone = models.CharField(max_length=132)
    address = models.CharField(max_length=64)
    sex = models.CharField(max_length=1, choices= SEX_TYPES)
    age = models.CharField(max_length=12)
    city = models.CharField(max_length=32)
    zip_code= models.CharField(max_length=16)
    created_date = models.DateTimeField(auto_now_add=True)
    save_by = models.ForeignKey(User, on_delete=models.PROTECT)

    class Meta:
        verbose_name = "Customer"
        verbose_name_plural = "Customers"

    def __str__(self):
        return self.name


class Invoice(models.Model):
    """
    Name: Invoice Name definition
    Description:
    author: evjeanbaptiste@gmail.com
    """
    INVOICE_TYPE = (
        ('R', 'REÇU'),
        ('P', 'PROFORMA FACTURE'),
        ('F', 'FACTURE'),

    )

    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    save_by = models.ForeignKey(User, on_delete=models.PROTECT)
    invoice_date_time = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10000, decimal_places=2)
    last_update_date = models.DateTimeField(null= True, blank=True)
    paid = models.BooleanField(default = False)
    invoice_type = models.CharField(max_length=1, choices= INVOICE_TYPE)
    comments = models.TextField(null= True, max_length=1000, blank= True)
    
    class Meta:
        verbose_name = "Invoice"
        verbose_name_plural ="Invoices"

    
    def __str__(self):

        return f"{self.customer.name}_{self.invoice_date_time}"
 
    @property
    def get_total(self):
        articles = self.article_set.all()   
        total = sum(article.get_total for article in articles)
        return total   



class Article(models.Model):
    """
    Name: Article Name definition
    Description:
    author: evjeanbaptiste@gmail.com
    """

    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    name = models.CharField(max_length=32)
    quantity = models.IntegerField()
    unit_price = models.DecimalField(max_digits=1000, decimal_places=2)
    total = models.DecimalField(max_digits=1000, decimal_places=2)

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural ='Articles'

    @property
    def get_total(self):
        total = self.quantity * self.unit_price
        return total 

fact_app/views.py
from django.shortcuts import render
from django.views import View
from .models import *
from django.contrib import messages

# Create your views here.

class HomeView(View):
    """Main View"""
    templates_name = "index.html"
    invoices = Invoice.objects.select_related('customer', 'save_by').all()
    context = {
        'invoices': invoices
    }

    def get(self, request, *args, **kwargs):

        return render(request, self.templates_name, self.context)

    def post(self, request, *args, **kwargs):
        
        return render(request, self.templates_name, self.context)

class AddCustomerView(View):
    """Add new customer"""
    template_name ="add_customer.html"

    def get(self, request, *args, **kwargs):

        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        
        data ={
            'name': request.POST.get('name'),
            'email': request.POST.get('email'),
            'phone': request.POST.get('phone'),
            'address': request.POST.get('address'),
            'sex': request.POST.get('sex'),
            'age': request.POST.get('age'),
            'city': request.POST.get('city'),
            'zip_code': request.POST.get('zip'),
            'save_by': request.user
        }

        try:
            created = Customer.objects.create(**data)

            if created:
                messages.success(request, "Customer registered successfully")
            else:
                messages.error(request,"Sorry, please try again the sent data is corrupt")

        except Exception as e:
            messages.error(request, f"Sorry, our system is detecting the following issues {e} ")
        return render(request, self.template_name)

templates/add_customer.html
{% extends "base.html" %}
{% load static %}

{% block content%}
<br><br>
<h1 class="text-capitalize text-center mx-10 bg-dark text-white">Register a new customer</h1>
<form  method="post">
  {% csrf_token %}

    <div class="row">
        <div class="form-group col-md-6">
            <label for="name"> Name </label>
            <input name="name" required type="text" class="form-control" id="name"
                placeholder="customer first and last name">
        </div>

        <div class="form-group col-md-4">
            <label for="email"> Email </label>
            <input name="email" required type="email" class="form-control" id="email" placeholder="customer email">
        </div>
        <div class="form-group col-md-2">
            <label for="phone"> Phone </label>
            <input name="phone" required type="number" class="form-control" id="phone"
                placeholder="customer phone number">
        </div>

    </div>

    <div class="row">
        <div class="form-group col-md-6">
            <label for="sex">Sex</label>
            <select name="sex" class="form-control" required id="sex">
                <option> Choose the gender .. </option>
                <option value="M">Male</option>
                <option value="F">Feminine</option>
            </select>
        </div>

        <div class="form-group col-md-6">
            <label for="age">Age</label>
            <select name="age" class="form-control" required id="age">
                <option> Choose the age range .. </option>
                <option value="0-15">0-15</option>
                <option value="0-15">15-25</option>
            </select>
        </div>

    </div>

    <div class="row">
        <div class="form-group col-md-12">
            <label for="addres"> Address </label>
            <input name="address" type="text" required type="text" class="form-control" id="address"
                placeholder="Customer address">
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-6">
            <label for="city"> City </label>
            <input name="city" type="text" class="form-control" id="city" placeholder="customer city">
        </div>

        <div class="form-group col-md-6">
            <label for="zip"> Zip code </label>
            <input name="zip" required type="text" class="form-control" id="zip"
                placeholder="customer zip code required">
        </div>
    </div>
<br>
    <button type="submit" class="btn btn-primary">Save</button>

</form>



{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css\styles.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'js\scripts.js' %}"></script>
    <title>Gestion des Factures</title>
</head>
<body>
   <!--header-->
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Invoice System</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
            Languages
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">English</a>
            <a class="dropdown-item" href="#">French</a>
          </div>
        </li>
        
      </ul>
      
    </div>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
            More option
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'add-customer' %}">Add Customer</a>
            <a class="dropdown-item" href="#">Add admin</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Staticstic</a>
          </div>
        </li>
        
      </ul>
      
    </div>
  </nav>
   <!-- end header-->
   <div class="container">

    <div class="wrapper">
      <br>
      {% for message in messages %}

      <div class="alert {{ message_tags}} alert-dismissible" role="alert">

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times</span>
        </button>
        {{ message|safe }}

      </div>
      {% endfor %}
    </div>


   </div>




   <div class="container">

  
    {% block content %}
    
    
    {% endblock content %}
  </div>

   <!--Footer-->

   <footer class="bg-light text-center text-dark">

    <!-- copyright -->

    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      invoice system © 2023 copyright:
      <a href="https://www.linkedin.com/in/jean-baptiste-ndouga-bakonga-71137138/">Jean Baptiste NDOUGA</a>
    </div>

    <!-- endcopyright -->

  </footer>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content%}

<br><br>

<div class="row">
    <a href="#" class="btn col-md-4 btn-primary">
        Register a new Invoice <span class="badge text-bg-secondary"></span>
    </a>

    <a href="#" class="btn col-md-4">
        Register a new Invoice <span class="badge text-bg-secondary"></span>
    </a>

    <a href="{% url 'add-customer' %}" class="btn col-md-4 btn-primary">
        Register a new customer <span class="badge text-bg-secondary"></span>
    </a>

</div>

<br><br>

<div class="form-group">

    <input id ="search" type="text" class="form-control" placeholder="Search">
</div>

<div>
    <table class="table">
        <thead>
            <tr>
            <th scope ="col">#</th>
            <th scope ="col">CUSTOMERS NAME</th>
            <th scope ="col">DATE</th>
            <th scope ="col">TOTAL</th>
            <th scope ="col">PAID</th>
            <th scope ="col">TYPE OF INVOICE</th>
            <th scope ="col">ACTION</th>
           </tr>

        </thead>

        <tbody id="myTable">
            {% if invoices %}

            {% for facture in invoices %}

            <tr>
                <th scope ="row">{{ facture.pk }}</th>
                <th>{{ facture.customer.name }}</th>
                <td>{{facture.invoice_date_time}}</td>
                <td>{{ facture.get_total }}</td>
                <td>
                    {% if facture.paid %}
                    <img src="{% static 'images/icon-yes.svg' %}" alt="True">
                    {% else %}
                    <img src="{% static 'images/icon-no.svg' %}" alt="False">
                    {% endif %}
                </td>

                <td>{{ facture.get_invoice_type_display  }}</td>
                <td>
                    <a href="" title="Detail" class="badge text-white bg-success">View</a>
                    <button id="btn-invoice-sup" type="button" data-toggle="modal" data-target="#supprimer" class="badge text-white bg-danger" title="Supprimer" data-id="{{ facture.pk }}" 
                    data-customer="{{ facture.customer.name}}"> Delete
                    </button>

                    <button id="btn-invoice-mod" type="button" data-toggle="modal" data-target="#Modifier" class="badge text-white bg-warning" title="Modifier" data-id="{{ facture.pk }}" 
                    data-customer="{{ facture.customer.name}}"> Modify
                    </button>
                </td>
            </tr>

            {% endfor %}

            {% else %}

            <p class="text-center text-white">No invoice found</p>
            {% endif %}

        </tbody>

    </table>
</div>

<!--Modal Modifier-->

<div class="modal fade " id="Modifier" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="True">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title text-dark text-center" id="exampleModalLabel">Modifier</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="True">&times</span>

                </button>
            </div>
           <form method="post">
            {% csrf_token %}

            <div class="modal-body">

                <input name="id_modified" type="hidden" id="id_modified">
                <label id="label_id" class="text-dark checkbox-inline"><strong id="strong_id">This bill has been paid ?</strong></label>

                <input type="radio" name="modified" id="html" value="True">
                <label class="text-white bg-primary" for="html">Yes</label>

                <input type="radio" name="modified" id="css" value="False">
                <label class="text-white bg-danger" for="css">No</label>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                 <button type="submit" class="btn-primary">Save</button>
            </div>
           </form>
        </div>
    </div>
</div>
<!--End Modal-->

<!--Modal Suppression-->
<div class="modal fade " id="supprimer" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="True">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title text-dark text-center" id="exampleModalLabel">Delete Invoice</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="True">&times</span>

                </button>
            </div>

            <div class="modal-body">
                <form method="post">
                    {% csrf_token %}
                <input name="id_supprimer" type="hidden" id="id_supprimer">
                <label id="label_id_s" class="text-dark checkbox-inline"><strong id="strong_id_s">Are you sure you want to delete the invoice ?</strong></label>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                 <button type="submit" class="btn-danger">Delete</button>
            </div>
           </form>
        </div>
    </div>
</div>
<!--End Modal-->



{% endblock content %}